### ISSUE TITLE
[Feature Request] Add Bytes as VectorRetriever content Input

### ISSUE THREAD

**Issue by Asher-hss** [camel-ai/camel#1001]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Currently, AutoRetriever only supports reading local files, which is not flexible enough for use. We hope to support Bytes as input.

**Comment by Wendong-Fan** [comment]
close as finished in https://github.com/camel-ai/camel/pull/1003
