### ISSUE TITLE
Smaller version of CAMEL

### ISSUE THREAD

**Issue by omni-georgio** [camel-ai/camel#1006]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

I am trying to deploy CAMEL to Replit, and it is very large. Could we have a smaller version of the package that only includes what is needed for basic agent setup and workforce?

**Comment by Wendong-Fan** [comment]
close this issue as have discussed with @omni-georgio , we can use `pip install camel-ai` to install basic version
