### ISSUE TITLE
[Feature Request] Support `synthesize` and `execute` mode for tool calling execution

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#1008]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Sometime we do not want to actually `execute` a tool. We want to support `mode` of `synthesize` for tool calling execution, in which the final return is synthesized via a LLM by taking either one of both of docstring and function body as input and output the final result.

**Comment by Wendong-Fan** [comment]
close as finished https://github.com/camel-ai/camel/pull/1140
