### ISSUE TITLE
[Question] Can Camel Facilitate Role-Playing Agent Interactions in a patient-Doctor Scenario?

### ISSUE THREAD

**Issue by LukeLIN-web** [camel-ai/camel#1019]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

I want to do experiment like https://github.com/joonspk-research/generative_agents . 

Can Camel handle role-playing interactions between two agents (for example, one as a doctor and another as patient), rather than just the Assistant and user, to complete a task? Thank you for any suggestion!

**Comment by lightaime** [comment]
Yes, you can check this: https://github.com/camel-ai/camel/blob/master/examples/ai_society/role_playing.py.
