### ISSUE TITLE
Live demo down

### ISSUE THREAD

**Issue by kevnoutsawo** [camel-ai/camel#103]
Hello,
The demo that is set up at https://f04f43d534b998d61a.gradio.live/ is currently down.
It only displays the following message: No interface is running right now

**Comment by Obs01ete** [comment]
Hi @kevnoutsawo. Thank you for spotting. We are working on it.

**Comment by lightaime** [comment]
The live demo is up: https://www.camel-ai.org/chatbot. Closed this issue.
