### ISSUE TITLE
[Feature Request] Add a better logger

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#105]

**Comment by dandansamax** [comment]
Hi everyone @lightaime  @camel-ai/camel-intern-team 

This issue becomes urgent since features like memory, storage, agent, function call, etc. are introduced. Also it will be important for our discord-frontend. Let me know if someone is interested.

**Comment by Wendong-Fan** [comment]
close as finished in https://github.com/camel-ai/camel/pull/701
