### ISSUE TITLE
[Feature Request] Update `readme.md` with features and some main feature code sinppets

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#1051]
### Required prerequisites

- [ ] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Update `readme.md` with features and some main feature code sinppets

**Comment by Wendong-Fan** [comment]
Guohao: put key features we supported in key modules in readme, we can refer to other how other opensource project's landing page
