### ISSUE TITLE
[BUG] The passed argument sequence in `ModelFactory` is in misalignment with models (e.g. `VLLMModel`)

### ISSUE THREAD

**Issue by LuciusMos** [camel-ai/camel#1074]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.2.1a

### System information

3.10.0 (default, Sep 23 2024, 20:37:00) [Clang 12.0.0 (clang-1200.0.32.28)] darwin
0.2.1a

### Problem description

The passed argument for initializing a new model is:
```python
        return model_class(
            model_type, model_config_dict, api_key, url, token_counter
        )
``` 

The init method of `VLLMModel` is:
```python
class VLLMModel:
    r"""vLLM service interface."""

    def __init__(
        self,
        model_type: str,
        model_config_dict: Dict[str, Any],
        url: Optional[str] = None,
        api_key: Optional[str] = None,
        token_counter: Optional[BaseTokenCounter] = None,
    ) -> None:
``` 

The sequence of `url` and `api_key` is wrong.

### Reproducible example code

The Python snippets:

```python

```

Command lines:

```bash

```

Extra dependencies:

```text

```

Steps to reproduce:

1.
2.
3.

**Comment by zhiyu-01** [comment]
Thanks @LuciusMos for raising this issue! It has been updated in https://github.com/camel-ai/camel/pull/998/files#diff-077932c374f2a38895c529ea49052e331841838a116bbd2eb727d7af060ebb34
