### ISSUE TITLE
[BUG] Available tools being added to conversation history multiple times when ChatAgent is stepped more than once with 'llama' model type

### ISSUE THREAD

**Issue by CaelumF** [camel-ai/camel#1119]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

29f926942543e1be4e1ec85de0ef56509ef38e90

### System information

*

### Problem description

The instructions for calling functions for llama models is added at each step in ChatAgent. Over time this builds up to functions being defined many times, filling up the context space.

### Reproducible example code

The Python snippets:

```python
import camel.toolkits
from camel.agents import ChatAgent
from camel.messages import BaseMessage
from camel.models import ModelFactory
from camel.types import ModelPlatformType

ollama_model = ModelFactory.create(
    model_platform=ModelPlatformType.OLLAMA,
    model_type="llama3.2",
    model_config_dict={"temperature": 0.4},
)

assistant_sys_msg = BaseMessage.make_assistant_message(
    role_name="Assistant",
    content="You are a helpful assistant.",
)
tools = camel.toolkits.MathToolkit().get_tools()

agent = ChatAgent(assistant_sys_msg, model=ollama_model, token_limit=4096, tools=tools)



user_msg = BaseMessage.make_user_message(
    role_name="User",
    content="""Say hi to CAMEL AI, one open-source community 
    dedicated to the study of autonomous and communicative agents.""",
)
assistant_response = agent.step(user_msg)
assistant_response2 = agent.step(user_msg)
len(agent.memory.get_context()[0]) # 7
```

agent.memory.get_context()[0] contains the instructions twice

### Expected behavior

That the function calling instructions are present only once

**Comment by Wendong-Fan** [comment]
Thanks @CaelumF  for raising this issue!
