### ISSUE TITLE
[Feature Request] Optimize GoogleScholarTool

### ISSUE THREAD

**Issue by koch3092** [camel-ai/camel#1121]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

When using GoogleScholarToolkit, there is no way to obtain author information.

### Solution

Detach GoogleScholarToolkit.get_author_detailed_info() and use Author as optional argument of related method.

**Comment by Wendong-Fan** [comment]
what kind of author information you need?

below is example output when use  current`GoogleScholarToolkit().get_author_detailed_info()`:
```
{'container_type': 'Author', 'filled': ['basics', 'indices', 'counts', 
'coauthors', 'publications', 'public_access'], 'scholar_id': 'JicYPdAAAAAJ', 
'source': <AuthorSource.AUTHOR_PROFILE_PAGE: 'AUTHOR_PROFILE_PAGE'>, 'name': 
'Geoffrey Hinton', 'url_picture': 'https://scholar.googleusercontent.com/
citations?view_op=view_photo&user=JicYPdAAAAAJ&citpid=2', 'affiliation': 
'Emeritus Prof. Computer Science, University of Toronto', 'organization': 
8515235176732148308, 'interests': ['machine learning', 'psychology', 
'artificial intelligence', 'cognitive science', 'computer science'], 
'email_domain': '@cs.toronto.edu', 'homepage': 'http://www.cs.toronto.edu/
~hinton', 'citedby': 853541, 'citedby5y': 560063, 'hindex': 186, 'hindex5y': 
137, 'i10index': 483, 'i10index5y': 368, 'cites_per_year': {1989: 2627, 1990: 
3589, 1991: 3766, 1992: 4091, 1993: 4573, 1994: 4499, 1995: 4090, 1996: 3935, 
1997: 3740, 1998: 3744, 1999: 3559, 2000: 3292, 2001: 3398, 2002: 3713, 2003: 
3670, 2004: 3393, 2005: 3813, 2006: 4168, 2007: 4558, 2008: 4349, 2009: 4784, 
2010: 5238, 2011: 5722, 2012: 6746, 2013: 9900, 2014: 12751, 2015: 18999, 
2016: 29932, 2017: 43675, 2018: 63544, 2019: 80800, 2020: 90523, 2021: 101735, 
2022: 104036, 2023: 106452, 2024: 76413}, 'coauthors': [{'container_type': 
'Author', 'filled': [], 'scholar_id': 'm1qAiOUAAAAJ', 'source': <AuthorSource.
CO_AUTHORS_LIST: 'CO_AUTHORS_LIST'>, 'name': 'Terrence Sejnowski', 
'affiliation': 'Francis Crick Professor, Salk Institute, Distingished 
Professor, UC San Diego'}, {'container_type': 'Author', 'filled': [], 
'scholar_id': 'RnoIxUwAAAAJ', 'source': <AuthorSource.CO_AUTHORS_LIST: 
'CO_AUTHORS_LIST'>, 'name': 'Vinod Nair', 'affiliation': 'Research Scientist, 
DeepMind'}, {'container_type': 'Author', 'filled': [], 'scholar_id': 
'ghbWy-0AAAAJ', 'source': <AuthorSource.CO_AUTHORS_LIST: 'CO_AUTHORS_LIST'>, 
'name': 'George E. Dahl', 'affiliation': 'Google Inc.'}, {'container_
```

**Comment by koch3092** [comment]
> what kind of author information you need?
> 
> below is example output when use current`GoogleScholarToolkit().get_author_detailed_info()`:
> 
> ```
> {'container_type': 'Author', 'filled': ['basics', 'indices', 'counts', 
> 'coauthors', 'publications', 'public_access'], 'scholar_id': 'JicYPdAAAAAJ', 
> 'source': <AuthorSource.AUTHOR_PROFILE_PAGE: 'AUTHOR_PROFILE_PAGE'>, 'name': 
> 'Geoffrey Hinton', 'url_picture': 'https://scholar.googleusercontent.com/
> citations?view_op=view_photo&user=JicYPdAAAAAJ&citpid=2', 'affiliation': 
> 'Emeritus Prof. Computer Science, University of Toronto', 'organization': 
> 8515235176732148308, 'interests': ['machine learning', 'psychology', 
> 'artificial intelligence', 'cognitive science', 'computer science'], 
> 'email_domain': '@cs.toronto.edu', 'homepage': 'http://www.cs.toronto.edu/
> ~hinton', 'citedby': 853541, 'citedby5y': 560063, 'hindex': 186, 'hindex5y': 
> 137, 'i10index': 483, 'i10index5y': 368, 'cites_per_year': {1989: 2627, 1990: 
> 3589, 1991: 3766, 1992: 4091, 1993: 4573, 1994: 4499, 1995: 4090, 1996: 3935, 
> 1997: 3740, 1998: 3744, 1999: 3559, 2000: 3292, 2001: 3398, 2002: 3713, 2003: 
> 3670, 2004: 3393, 2005: 3813, 2006: 4168, 2007: 4558, 2008: 4349, 2009: 4784, 
> 2010: 5238, 2011: 5722, 2012: 6746, 2013: 9900, 2014: 12751, 2015: 18999, 
> 2016: 29932, 2017: 43675, 2018: 63544, 2019: 80800, 2020: 90523, 2021: 101735, 
> 2022: 104036, 2023: 106452, 2024: 76413}, 'coauthors': [{'container_type': 
> 'Author', 'filled': [], 'scholar_id': 'm1qAiOUAAAAJ', 'source': <AuthorSource.
> CO_AUTHORS_LIST: 'CO_AUTHORS_LIST'>, 'name': 'Terrence Sejnowski', 
> 'affiliation': 'Francis Crick Professor, Salk Institute, Distingished 
> Professor, UC San Diego'}, {'container_type': 'Author', 'filled': [], 
> 'scholar_id': 'RnoIxUwAAAAJ', 'source': <AuthorSource.CO_AUTHORS_LIST: 
> 'CO_AUTHORS_LIST'>, 'name': 'Vinod Nair', 'affiliation': 'Research Scientist, 
> DeepMind'}, {'container_type': 'Author', 'filled': [], 'scholar_id': 
> 'ghbWy-0AAAAJ', 'source': <AuthorSource.CO_AUTHORS_LIST: 'CO_AUTHORS_LIST'>, 
> 'name': 'George E. Dahl', 'affiliation': 'Google Inc.'}, {'container_
> ```

I hope to get all the paper content of author. Can this be achieved with current tools? Or maybe we can only get the brief content of the paper now?

**Comment by Wendong-Fan** [comment]
> > what kind of author information you need?
> > below is example output when use current`GoogleScholarToolkit().get_author_detailed_info()`:
> > ```
> > {'container_type': 'Author', 'filled': ['basics', 'indices', 'counts', 
> > 'coauthors', 'publications', 'public_access'], 'scholar_id': 'JicYPdAAAAAJ', 
> > 'source': <AuthorSource.AUTHOR_PROFILE_PAGE: 'AUTHOR_PROFILE_PAGE'>, 'name': 
> > 'Geoffrey Hinton', 'url_picture': 'https://scholar.googleusercontent.com/
> > citations?view_op=view_photo&user=JicYPdAAAAAJ&citpid=2', 'affiliation': 
> > 'Emeritus Prof. Computer Science, University of Toronto', 'organization': 
> > 8515235176732148308, 'interests': ['machine learning', 'psychology', 
> > 'artificial intelligence', 'cognitive science', 'computer science'], 
> > 'email_domain': '@cs.toronto.edu', 'homepage': 'http://www.cs.toronto.edu/
> > ~hinton', 'citedby': 853541, 'citedby5y': 560063, 'hindex': 186, 'hindex5y': 
> > 137, 'i10index': 483, 'i10index5y': 368, 'cites_per_year': {1989: 2627, 1990: 
> > 3589, 1991: 3766, 1992: 4091, 1993: 4573, 1994: 4499, 1995: 4090, 1996: 3935, 
> > 1997: 3740, 1998: 3744, 1999: 3559, 2000: 3292, 2001: 3398, 2002: 3713, 2003: 
> > 3670, 2004: 3393, 2005: 3813, 2006: 4168, 2007: 4558, 2008: 4349, 2009: 4784, 
> > 2010: 5238, 2011: 5722, 2012: 6746, 2013: 9900, 2014: 12751, 2015: 18999, 
> > 2016: 29932, 2017: 43675, 2018: 63544, 2019: 80800, 2020: 90523, 2021: 101735, 
> > 2022: 104036, 2023: 106452, 2024: 76413}, 'coauthors': [{'container_type': 
> > 'Author', 'filled': [], 'scholar_id': 'm1qAiOUAAAAJ', 'source': <AuthorSource.
> > CO_AUTHORS_LIST: 'CO_AUTHORS_LIST'>, 'name': 'Terrence Sejnowski', 
> > 'affiliation': 'Francis Crick Professor, Salk Institute, Distingished 
> > Professor, UC San Diego'}, {'container_type': 'Author', 'filled': [], 
> > 'scholar_id': 'RnoIxUwAAAAJ', 'source': <AuthorSource.CO_AUTHORS_LIST: 
> > 'CO_AUTHORS_LIST'>, 'name': 'Vinod Nair', 'affiliation': 'Research Scientist, 
> > DeepMind'}, {'container_type': 'Author', 'filled': [], 'scholar_id': 
> > 'ghbWy-0AAAAJ', 'source': <AuthorSource.CO_AUTHORS_LIST: 'CO_AUTHORS_LIST'>, 
> > 'name': 'George E. Dahl', 'affiliation': 'Google Inc.'}, {'container_
> > ```
> 
> I hope to get all the paper content of author. Can this be achieved with current tools? Or maybe we can only get the brief content of the paper now?

It's not doable automaticlly, see comment: https://github.com/camel-ai/camel/pull/997#discussion_r1789827602
but we have `GoogleScholarToolkit().get_full_paper_content_by_link(pdf_url="xx")` to support this
