### ISSUE TITLE
[BUG] Fix `camel-data-explorer` on huggingface

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#1195]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.2.9

### System information

0.2.9

### Problem description

https://huggingface.co/spaces/camel-ai/camel-data-explorer

### Reproducible example code

===== Application Startup at 2024-11-19 16:30:14 =====

Traceback (most recent call last):
  File "/home/user/app/app.py", line 2, in <module>
    from apps.data_explorer.downloader import download_data
  File "/home/user/app/apps/data_explorer/downloader.py", line 18, in <module>
    from huggingface_hub.utils._errors import RepositoryNotFoundError
ModuleNotFoundError: No module named 'huggingface_hub.utils._errors'
Traceback (most recent call last):
  File "/home/user/app/app.py", line 2, in <module>
    from apps.data_explorer.downloader import download_data
  File "/home/user/app/apps/data_explorer/downloader.py", line 18, in <module>
    from huggingface_hub.utils._errors import RepositoryNotFoundError
ModuleNotFoundError: No module named 'huggingface_hub.utils._errors'

**Comment by Wendong-Fan** [comment]
bug is fixed
