### ISSUE TITLE
[Feature Request] Cookbook to showcase o1 data generation

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#1215]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

math, code, science data generation using wolfamalph etc..

**Comment by zjrwtx** [comment]
some experiment result and it opensource in https://github.com/zjrwtx/o1datagene

![image](https://github.com/user-attachments/assets/a30c7cfb-95c7-4879-b7b4-d0171831ff98)

**Comment by zjrwtx** [comment]
already add pr:https://github.com/camel-ai/camel/pull/1274
