### ISSUE TITLE
[BUG]  Colab notebook is missing "from colorama import Fore" 

### ISSUE THREAD

**Issue by foolsh** [camel-ai/camel#128]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

latest

### System information

Google Colab notebook

### Problem description

Colab notebook fails to run adding "from colorama import Fore" fixes.  Thanks.

### Reproducible example code

The Python snippets:

```python

```

Command lines:

```bash

```

Extra dependencies:

```text

```

Steps to reproduce:

1.
2.
3.

**Comment by lightaime** [comment]
Good catch! I deleted it by mistake. Thanks!
