### ISSUE TITLE
[Question] I want to know can the camel choose the role automatically according to the preliminary?

### ISSUE THREAD

**Issue by feihuamantian** [camel-ai/camel#129]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

According to your design ,  wo need to choose the user role and assistantt role first. I think can we not need think what role wo need, the camel can autonomously choose the roles  according to the preliminary idea?

**Comment by lightaime** [comment]
Hi @feihuamantian, thanks for the good question. Yes, it is possible. I also wanted to have this feature :) Will add it soon.

**Comment by lightaime** [comment]
Close by https://github.com/camel-ai/camel/pull/247
