### ISSUE TITLE
[Feature Request] Control code excution in `CodePrompt.execute`

### ISSUE THREAD

**Issue by dandansamax** [camel-ai/camel#150]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Now the code execution of Python is using bare `exec`, which can cause arbitrary code execution and system crash. Moreover, the value in `exec` cannot be captured by outer program, which add difficulty for some agent implementation.

### Solution

We can use `ast` in python to analysis generated code and control the execution of interpreter.

**Comment by lightaime** [comment]
That is an awesome idea! Thanks @dandansamax.

**Comment by yhyu13** [comment]
@dandansamax Would you like to elaborate more on how `ast` could identify potential risks in generated py code?

**Comment by dandansamax** [comment]
> @dandansamax Would you like to elaborate more on how `ast` could identify potential risks in generated py code?

Sure. Actually it was inspired by the implementation of the hugging face agent. See [python_interpreter.py](https://github.com/huggingface/transformers/blob/8f093fb799246f7dd9104ff44728da0c53a9f67a/src/transformers/tools/python_interpreter.py).

The basic idea is to parse the generated python code through `ast.parse()` and check all subtress in the "ast". We only allow several types of python expressions to execute, such as variable assign, function call, ... And some expressions like `import` are forbidden. Moreover, the code is executed manually (instead of exec). So the execution process in more secure and controllable.

**Comment by dandansamax** [comment]
#182 has been merged. Close this issue.
