### ISSUE TITLE
[Feature Request] Refactor code to simplify the concepts

### ISSUE THREAD

**Issue by Obs01ete** [camel-ai/camel#163]
### Motivation

We need to clean up code so that the API is easier to study and use. List of required changes:
- [x] Remove `UserChatMessage` and `AssistantChatMessage`
- [x] Remove `AssistantSystemMessage` and `UserSystemMessage`
- [x] Rename `role` from `ChatMessage` into `role_at_backend`
- [x] Remove `role` from `ChatMessage` altogether
- [ ] Make `BaseMessage`, `ChatMessage`, `SystemMessage` a `frozen=True` dataclass
- [x] Remove `def __getattribute__` from BaseMessage (https://github.com/camel-ai/camel/pull/168)
- [ ] Replace type of `content` in `BaseMessage` with `TextPrompt`
- [ ] Rename `model` to `model_type`
- [x] Fix `mode_type` typos (https://github.com/camel-ai/camel/pull/166, https://github.com/camel-ai/camel/pull/169)
- [x] Extract RolePlaying into a separate `societies` package
- [ ] Strict signature match for BaseAgent child classes

**Comment by Obs01ete** [comment]
I think mostly the refectoring is done. The remaining open points we will address later on.

**Comment by dandansamax** [comment]
What should we remove role from ChatMessage? I'm planning to replace `ChatAgent.stored_messages` with memory module. It's inconvenient for memory API design if not all message-related information stores in `BaseMessage`.
