### ISSUE TITLE
[Feature Request] Support streaming output and remove `print_text_animated`

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#178]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

The current logger is not true streaming. To reduce logging time, we should support true streaming.

### Solution

A tutorial about streaming completion is available here: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb.

**Comment by zechengz** [comment]
As discussed in this PR https://github.com/camel-ai/camel/pull/184 comments that we are not going to support terminal prints in the near future. So, I don't support stream mode with any "real time" printing.
Also to make current debugging easier, keep `print_text_animated` in `camel/agents/embodied_agent.py`, `camel/agents/critic_agent.py` and `camel/human.py` makes more sense to me.
So I am going to close this ticket. Please let me know if you have any questions or suggestions.
