### ISSUE TITLE
[Feature Request] Allow different models for `assistant`, `user`, `task_specify_agent`, and `critic` etc in the `RolePlaying`

### ISSUE THREAD

**Issue by zechengz** [camel-ai/camel#190]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

As number of LLMs is increasing, many LLMs are designed for different tasks and even have different price. So, it's useful to let user specify different models for each agent in `RolePlaying`. Followings are some examples:

**Example 1**
User may have cost concern for `RolePlaying` when they use for example GPT4 for all `assistant`, `user` and `critic`. One way to lower cost might be using GPT3.5 for `assistant` and `user` but GPT4 for `critic`. In this way user can have some flexibility to control the cost of `RolePlaying` but still maintain some quality of `RolePlaying`.

**Example 2**
Now there are many LLMs are trained to optimize some specific tasks. In the future, it's possible that user can use a specific LLM for `assistant` but another LLM for `user` during `RolePlaying` collaboration. Maybe in this way the `RolePlaying` can have better performance.

### Solution

Allow different models for `assistant`, `user`, `task_specify_agent`, and `critic` etc in the `RolePlaying`

**Comment by lightaime** [comment]
Thanks @zechengz. This is a great idea. This can be done by setting `model_type` in `*_agent_kwargs`. So let's say if `*_agent_kwargs` includes `model_type`, we override the default one. WDYT?

**Comment by Obs01ete** [comment]
If we want fine grained control over the model backends, we'd better implement the dependency injection pattern: feed every agent with a pre-constructed model backend. See https://stackify.com/dependency-injection/

**Comment by zechengz** [comment]
I checked that current model backend is defined by `model_type` and `model_config_dict`.
If we just have these two params for model backend, IMO we can just allow user to put them to `*_agent_kwargs`. And we construct each agent by getting `model_type` and `model_config_dict` from each `*_agent_kwargs` (if they are specified).

As current model backend is constructed within each `Agent`, for now IMO it's easier to pass user specified `model_type` and `model_config_dict` (from `*_agent_kwargs`) directly.
