### ISSUE TITLE
[BUG] Flacky test `test_chat_agent_batch_stream_same_output`

### ISSUE THREAD

**Issue by Obs01ete** [camel-ai/camel#199]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

master/HEAD

### System information

---

### Problem description

Test `test_chat_agent_batch_stream_same_output` is flaky, ie does not always pass in CI (1 fail out of 5 runs).

### Reproducible example code

The Python snippets:

Command lines:

```bash
pytest test/agents/test_chat_agent.py
```

**Comment by zechengz** [comment]
Thanks, I will take a look.

**Comment by zechengz** [comment]
I found that when using `stream=True`, sometimes it will stuck at 
```python
response = openai.ChatCompletion.create(messages=messages_openai, ...
```
This seems to be a known issue from openai side https://github.com/openai/openai-python/issues/399

I will probably create a PR that in that test use a timeout checking. If some time (for example such as 10 seconds) reached but still have not finished the test, mark that test as passed.

**Comment by zechengz** [comment]
I re-checked some errors in the test, such as https://github.com/camel-ai/camel/actions/runs/5485571323/jobs/9994538405?pr=210.
I am not sure why sometimes stream mode can return extra new lines. Also, I can't find any source for this.

The only information I got is from ChatGPT 😂
```
The OpenAI ChatGPT model can sometimes produce slightly different results when used in stream (also known as "conversational") mode compared to batch mode. The main reason for this discrepancy is that the model processes text differently depending on the context in which it's used.

In stream mode, the model receives the conversation history as a series of alternating messages between the user and the assistant. The model generates a response based on the entire conversation history, taking into account the previous messages as context.

In batch mode, on the other hand, the model receives all the messages at once as a single input. The messages are typically concatenated together, separated by special tokens or other delimiters, to form a single string. The model generates responses without considering individual messages separately, treating the entire batch as a single context.

Due to these differences in processing, the model might produce additional new lines or formatting variations when used in stream mode. It's important to note that these differences are usually minor and do not significantly affect the meaning or quality of the responses.
```
I will make that test only checking stream mode instead of compare results to the batch one.
