### ISSUE TITLE
[BUG] Mypy errors in examples

### ISSUE THREAD

**Issue by Obs01ete** [camel-ai/camel#208]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

master/HEAD

### System information

---

### Problem description

These are the remaining mypy errors in examples that I am not able to fix:
```bash
mypy --install-types --non-interactive --namespace-packages -p examples
examples/misalignment/task_generation.py:34: error: "SystemMessageGenerator" has no attribute "from_role"  [attr-defined]
examples/misalignment/task_generation.py:80: error: Unexpected keyword argument "generate_tasks_prompt_path" for "AISocietyTaskPromptGenerator"  [call-arg]
```

### Reproducible example code

Command lines:

```bash
mypy --install-types --non-interactive --namespace-packages -p examples
```

**Comment by Obs01ete** [comment]
@lightaime can we have someone fix this?

**Comment by lightaime** [comment]
@hammoudhasan could you take this one?
