### ISSUE TITLE
[BUG] Multiple set_output_language calls

### ISSUE THREAD

**Issue by Obs01ete** [camel-ai/camel#215]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

master/HEAD

### System information

---

### Problem description

Multiple ChatAgent.set_output_language() calls in a row result in mumbo-jumbo system_message.

### Reproducible example code

The Python snippets:

```python
agent = ChatAgent(...)
agent.set_output_language("Arabic")
agent.set_output_language("Chinese")
agent.set_output_language("Greek")
```

In general fields must be immutable, or at least updated by write, not by read-write.

**Comment by lightaime** [comment]
Thanks. We will fix it.
