### ISSUE TITLE
[Feature Request] Intergrate `LLaMA 2` to `CAMEL`

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#225]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Intergrate LLaMA 2 to CAMEL

**Comment by MorphlingEd** [comment]
Could we individually request access to LLaMA(1 or 2) by using the information of KAUST and the paper CAMEL (as required by *Previous related publications*)? Or only one of us will do this and then share?
