### ISSUE TITLE
[Feature Request] Support  `Azure` OpenAI models

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#231]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

People are interested in setting up Azure OpenAI models. We can add Azure OpenAI models to https://github.com/camel-ai/camel/tree/master/camel/models.

**Comment by lightaime** [comment]
@hammoudhasan can you take this issue? It is related to what we will do.

**Comment by L4zyy** [comment]
Hi, @lightaime , I have integrated Azure OpenAI API into Camel and updated the corresponding files. Would it be okay for me to make a pull request?

**Comment by Wendong-Fan** [comment]
finished https://github.com/camel-ai/camel/pull/733
