### ISSUE TITLE
[BUG] `original_task` is not passed to the right argument in `RolePlaying` in the agent demo app

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#232]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.1.0

### System information

3.10.11 (main, May 15 2023, 19:29:30) [Clang 14.0.6 ] darwin
0.1.0

### Problem description

The `original_task` is sent to `critic_role_name` instead of `task_prompt`.

 https://github.com/camel-ai/camel/blob/63a9444ff30c4619dad63d9a5c87ecc6c47d5385/apps/agents/agents.py#L190

should be `task_prompt=original_task`.

### Reproducible example code

The Python snippets:

```python

```

Command lines:

```bash

```

Extra dependencies:

```text

```

Steps to reproduce:

1.
2.
3.

**Comment by Obs01ete** [comment]
@lightaime I wonder why do we have task_prompt as kwarg? Is there any use of task_prompt if it is an empty string? I'd prefer to make it a positional arg and bubble it up.
```
class RolePlaying:
    def __init__(
        ...
        task_prompt: str = "",
```

**Comment by lightaime** [comment]
I guess I reopen it by accident
