### ISSUE TITLE
[Feature Request] Some suggestions about project structure

### ISSUE THREAD

**Issue by dandansamax** [camel-ai/camel#241]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

I am in the process of fixing an problem where pytest fail to pass after executing `pip install -e .` because missing dependencies `mock` and `gradio`. These two packages never appears except the github action files. During this process, I've identified an underlying problem within our project structure that needs to be addressed.

Our project currently utilizes two different systems to describe dependencies: `requirements.txt` and the `[tool.poetry.dependencies]` section in `pyproject.toml`. When the `pip install -e .` command is executed, it actually utilizes the latter. This dual structure can create confusion for users trying to understand which dependencies are required for development and which are needed for using camel as a library.

I have referred to discussions on this matter at [pypa/pip#8049](https://github.com/pypa/pip/issues/8049) and [pypa/pip#11584](https://github.com/pypa/pip/issues/11584). A relevant quote that caught my attention is:

> I don’t think that installing dependencies and running a project uninstalled is a pattern we want to encourage. If you’re running your project uninstalled, it’s probably an application, not a library, and applications should be using a requirements file. See https://caremad.io/posts/2013/07/setup-vs-requirement/

With this in mind, I believe that both `requirements.txt` and `[tool.poetry.dependencies]` have their respective roles. Specifically, requirements.txt should be used to run the examples, while the `[tool.poetry.dependencies]` section should define the building process of the "camel" library. These two elements should be treated separately, and we must ensure that our documentation reflects this to avoid confusion.

### Solution

I think the best solution would be seperate "camel" library and its exmaples and apps into two repos. The library repo only contains `pyproject.toml` and the exmaples repo only contains `requirements.txt`.

### Alternatives

Or we can just move `requirements.txt` from the project root to `apps/` and `exmaples/` dirs. But then we have to choose whether to include `mock` and `gradio` in `[tool.poetry.dependencies]`.

**Comment by Obs01ete** [comment]
Thanks for bringing up this issue. I am not sure how we've got here but seems that requirements.txt are not used at all. The source of dependencies is pyproject.toml. I suggest to make sure that requirements.txt are not in fact used, and then delete this file. @dandansamax can you try this?

**Comment by lightaime** [comment]
Requirements.txt can be removed safely. But we do need gradio and mock in
pyproject.toml for the dev mode installation.

**Comment by Obs01ete** [comment]
I am good with moving everything into pyproject.toml. Left comments on the PR.

**Comment by dandansamax** [comment]
> But we do need gradio and mock in pyproject.toml for the dev mode installation.

If we don't do that, a user setting up the environment for the first time with pip or poetry and then running `pytest .` will encounter an import error. We should place them somewhere other than GitHub Actions.
