### ISSUE TITLE
[BUG] test `tests_search_wiki_with_ambiguity` fails from time to time

### ISSUE THREAD

**Issue by dandansamax** [camel-ai/camel#260]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.1.0

### System information

pass

### Problem description

```
# test/functions/test_search_functions.py::tests_search_wiki_with_ambiguity()

def tests_search_wiki_with_ambiguity():
    expected_output = (
        "New York, often called New York State, is a state in the"
        " Northeastern United States. A Mid-Atlantic state, New York"
        " borders New England, and has an international border with Canada."
        " With almost 19.7 million residents, it is the fourth-most populous "
        "state in the United States and seventh-most densely populated as of "
        "2022. New York is the 27th-largest U.S. state by area, with a total "
        "area of 54,556 square miles (141,300 km2).New York has a varied "
        "geography. The southeastern part of the state, known as Downstate, "
        "encompasses New York City (the most populous city in the United "
        "States), Long Island (the most populous island in the United States)"
        ", and the lower Hudson Valley.")
    assert search_wiki("New York") == expected_output
```

This test should be removed or modified since wikipeida updates from time to time, which crashing the test.

### Reproducible example code

pass

**Comment by MorphlingEd** [comment]
Have submitted a new PR for this problem. We can simply define `expect_output` by the summary of entity `New York (state)` to validate the content.
