### ISSUE TITLE
Data I/O

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#275]
💡 **User Story:**
As an AI engineer,
I want to add data input capability to CAMEL
So that our user can take different kinds of files as input

🛒 **Types of Changes:**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

🚀 **Acceptance Criteria:**
1. Functional code can handle with: 
.docx
.pdf
.txt
.html
.json
Convert information from all these file types into string

2. Apply the functional code to CAMEL master branch successfully, and pass all tests.

🔀 **Related User Stories:**
No story related

🛠️ **Technical Details:**
Use BytesIO, reference Langchain data input module

📑 **Tasks:**
.docx
.pdf
.txt
.html
.json

🔑 **Dependencies:**
No dependencies needed

🤝 **Required Prerequisites:**
- [x] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

**Comment by dandansamax** [comment]
Could you check `camel/memory/lossless_storage.py` in branch `memory_liubo`? I think the data IO design is highly related to the memory design.

**Comment by Wendong-Fan** [comment]
Hi Tianqi, sorry for the late reply, sure I will check this

**Comment by dandansamax** [comment]
#281 is merged. Close this.
