### ISSUE TITLE
[Feature Request] Optimize Issue and PR templates

### ISSUE THREAD

**Issue by dandansamax** [camel-ai/camel#278]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Templates now are too redundant for daily development. We can try to make them more brief.

**Comment by lightaime** [comment]
Sounds good!
