### ISSUE TITLE
[Feature Request] Web UI for muti-agent

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#299]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

For muti-agent, we need a UI to better show the demo

### Solution

Use Streamlit to build the web UI

### Alternatives

Gradio as an alternative framework

**Comment by Obs01ete** [comment]
The UI demo must go into apps folder. Also, where is the core functionality for multiagent? We do not have a multiagent society yet.

**Comment by Wendong-Fan** [comment]
> The UI demo must go into apps folder. Also, where is the core functionality for multiagent? We do not have a multiagent society yet.

Will add the UI under apps folder, currently the functionality has not been ready but I can start developing the UI framework first.
