### ISSUE TITLE
[Feature Request] Add "good first issue" tags

### ISSUE THREAD

**Issue by dandansamax** [camel-ai/camel#304]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Please choose some good first issues for new contributer that can quickly get started.

**Comment by Lymah123** [comment]
Hi, has anyone started working on the issue?

**Comment by 149189** [comment]
Hey! Can I work on this issue?

**Comment by dandansamax** [comment]
> Hey! Can I work on this issue?

Hi @149189. Of course! Please go ahead and let us know if you need any clarifications or assistance. We appreciate your contribution!
