### ISSUE TITLE
[Feature Request] Unsafe code execution support

### ISSUE THREAD

**Issue by dandansamax** [camel-ai/camel#331]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Current implementation only allows execute safe python codes. To give user more flexibility, we should add unsafe code execution mode.

### Solution

Use python `subprocess` package to run commands.

**Comment by atharvaBaste** [comment]
@dandansamax what does safe python mode mean?

I wanted to execute LLM generated code and save the produced results, (P.S. does this mean unsafe?), so any idea how to do this instead of just copy pasting?

**Comment by atharvaBaste** [comment]
hi @dandansamax ,

Thanks for letting know the framework better.

So subprocess is like parallel programming right? We try to save the main process while we may risk the new process. Also we can try sandboxing .

I had a question though - So in Autogen i didn't encounter any such restriction to execute also it generated and executed my prompts automatically, so any idea how does Autogen ensure this malicious non execution or has it accepted this risk afayk??

**Comment by dandansamax** [comment]
> So subprocess is like parallel programming right?

Yes. Also the sandboxing idea is good, we should try to implement it.

I'm not so familiar with Autogen, but after checking its code, I believe it uses `subprocess` to execute code and having two mode. If `use_docker` is not specified, it will run the code natively in the host, otherwise it will start up a docker image to run it.

**Comment by dandansamax** [comment]
The sandboxing idea is good, we should try to implement it.
