### ISSUE TITLE
[BUG] Naming inconsistency of `model` in `ChatAgent` and `model_type` in elsewhere

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#337]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.1.0

### System information

```
3.10.11 (main, May 15 2023, 19:29:30) [Clang 14.0.6 ] darwin
0.1.0
```

### Problem description

The naming of `model` in `ChatAgent` is inconsistent with `model_type` in elsewhere. Let's change `model` in `ChatAgent` to `model_type` as well.

### Reproducible example code

N/A

**Comment by riverfor** [comment]
Would you like me to modify the model parameters in the init function of multiple agents in camel/agents to align with the model_type? This will ensure consistency with the model_type in the init function of various models in camel/model.

**Comment by lightaime** [comment]
> Would you like someone to modify the model parameters in the init function of multiple agents in camel/agents to align with the model_type? This will ensure consistency with the model_type in the init function of various models in camel/model.

Yes, just renaming the model parameters to model_type to  e consistent with other files.

**Comment by FUYICC** [comment]
Hi, I noticed that the initial function of ChatAgent in agents/chat_agent.py is not in the same format as in other agents, is that what you are talking about? If this hasn't been modified, I can help change this.

**Comment by lightaime** [comment]
Hi @FUYICC. This issue is about renaming the argument `model` in [`agents`](https://github.com/camel-ai/camel/tree/master/camel/agents) to `model_type` since `model_type` is used in other modules like [`models`](https://github.com/camel-ai/camel/tree/master/camel/models). Changing the name will make it more consistent. Not sure if @riverfor is working on it. Otherwise, please feel free to have a try.

**Comment by dandansamax** [comment]
#366 is merged.
