### ISSUE TITLE
[Feature Request] Users need the OPENAI_API_BASE_URL for the OPENAI proxy to function optimally

### ISSUE THREAD

**Issue by riverfor** [camel-ai/camel#338]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

In addition to the OPENAI_API_KEY, users also need the OPENAI_API_BASE_URL for the OPENAI proxy to function optimally. This is particularly important as a lot of developers use the OpenAI proxy to develop.

### Solution

Consider incorporating the OPENAI_API_BASE_URL as a discretionary setting. If a user specifies this setting, it will be operational. If not, the default should be https://api.openai.com/v1.

**Comment by lightaime** [comment]
Thanks @riverfor. This is a good suggestion! Please feel free to open a PR on this. I think modifying this file: https://github.com/camel-ai/camel/blob/master/camel/models/openai_model.py should work.

**Comment by riverfor** [comment]
OK, I will give it a try.
