### ISSUE TITLE
[BUG] Conflict between"isort" and "yapf" on long import statement

### ISSUE THREAD

**Issue by dandansamax** [camel-ai/camel#343]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.1.0

### System information

.

### Problem description

On the same code, `isort` result:

```
from camel.memories.context_creators.important_based import (
    ImportantBasedContextCreator,
)
```

yapf result:

```
from camel.memories.context_creators.important_based import (
    ImportantBasedContextCreator, )
```

pre-commit check can never pass on this situation.

### Reproducible example code

The Python snippets:

```python

```

Command lines:

```bash

```

Extra dependencies:

```text

```

Steps to reproduce:

1.
2.
3.

### Expected behavior

Modify yapf configuration.

**Comment by Wendong-Fan** [comment]
After moving to ruff this bug is also fixed, thanks @ocss884 !
