### ISSUE TITLE
[Question] Rename `utils.functions` to `utils.common`

### ISSUE THREAD

**Issue by dandansamax** [camel-ai/camel#347]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

Since we added functions package for "openAI function call", it may be better to rename `utils.functions` to avoid confusion. I suggest to rename to `utils.common` as most python libs do.

**Comment by lightaime** [comment]
Sounds good to me. Maybe let's use the plural `utils.commons`.

**Comment by dandansamax** [comment]
#351 merged
