### ISSUE TITLE
[Question] what's the difference between camel and chatarena?

### ISSUE THREAD

**Issue by HuXinjing** [camel-ai/camel#383]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

they are as same as twins.

**Comment by lightaime** [comment]
Great question. I love Chatarena! It is a great work. CAMEL (2023.3.21) and Chatarena (2023.4.5) released almost the same time. You can read Yuxiang's tweet: https://twitter.com/YuxiangJWu/status/1643633046208249856. CAMEL is about more task-oriented and Chatarena is more about simulating conversation.

**Comment by HuXinjing** [comment]
> Great question. I love Chatarena! It is a great work. CAMEL (2023.3.21) and Chatarena (2023.4.5) released almost the same time. You can read Yuxiang's tweet: https://twitter.com/YuxiangJWu/status/1643633046208249856. CAMEL is about more task-oriented and Chatarena is more about simulating conversation. You should choose based on your need.

Nice, it would be a good start for me to read your paper
