### ISSUE TITLE
[Feature Request] Integrate open source embedding model

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#385]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

integrate e5-large-v2 embedding model to camel

**Comment by dandansamax** [comment]
How about converting this issue to a roadmap that adds more embedding models. It can be a good first issue.

**Comment by Wendong-Fan** [comment]
Hi @dandansamax , I agree that incorporating a roadmap for integrating additional open-source models is an excellent initiative for newcomers. However, I believe our focus would be better served by concentrating on open-source Large Language Models (LLMs) rather than expanding the range of open-source embedding models. This approach could potentially offer more substantial benefits and advancements in our project. What are your thoughts on this? 

@lightaime
