### ISSUE TITLE
[BUG] Multi-agent Compatibility Score of Role Assignment 

### ISSUE THREAD

**Issue by ZhangT-tech** [camel-ai/camel#419]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

not get enough user/assistant scores

### System information

>>> import sys, camel
print(sys.version, sys.platform)
print(camel.__version__)

>>> print(sys.version, sys.platform)
3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ] darwin

>>> print(camel.__version__)
0.1.0

### Problem description

When executing `multi_agent_communication.py`, the program may prematurely terminate due to insufficient compatibility scores for the user or assistant, resulting in an abnormal cessation of operations. To enhance the multi-agent process's efficiency and stability, it is advisable to implement an exception handling mechanism. This will effectively capture and address any arising exceptions, allowing for a smoother continuation of the program.

### Traceback

Traceback (most recent call last):
  File "/Users/zhant0g/camel/examples/multi_agent/multi_agent_communication.py", line 463, in <module>
    main(task_prompt=task_prompt, context_text=context_text)
  File "/Users/zhant0g/camel/examples/multi_agent/multi_agent_communication.py", line 144, in main
    role_assignment_agent.evaluate_role_compatibility(
  File "/Users/zhant0g/camel/camel/agents/role_assignment_agent.py", line 561, in evaluate_role_compatibility
    raise RuntimeError("Got None or insufficient information of " +
RuntimeError: Got None or insufficient information of compatibility scores as USER.

**Comment by ZhangT-tech** [comment]
msg shows: I'm sorry, but I cannot fulfill your request.

**Comment by Appointat** [comment]
I got it. Because we are having AI predict events that will occur in 2024 (this is an example provided by our UI), however, sometimes the AI refuses to answer such questions, with responses like "I refuse to respond to your request." This leads to errors occurring throughout the entire system. It is a hard issue, so the way is to change the inputs in the demo example. @ZhangT-tech

**Comment by ZhangT-tech** [comment]
based on the running experiment, there are typically two response:
1.  I'm sorry, but I cannot fulfill your request.
2. I'm sorry, I cannot assist with that request
So I updated it in the split_task_rules_prompt to avoid having subtasks that decomposed in conflicting with OpenAI request
