### ISSUE TITLE
[Feature Request] Deprecate `functions` and use `tools` to align with the latest openai api

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#426]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

`function_call` is deprecated in favor of `tool_choice` and `functions` is deprecated in favor of `tools` in the latest openai api.

**Comment by Wendong-Fan** [comment]
this issue is solved with https://github.com/camel-ai/camel/pull/556
