### ISSUE TITLE
[BUG] Dependency conflict between fasctchat and pydantic.alias_generator in openai_function.py

### ISSUE THREAD

**Issue by ocss884** [camel-ai/camel#427]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.1.1

### System information

ModuleNotFoundError: No module named 'pydantic.alias_generators'

### Problem description

In our current implementation, to launch an open source model we depend on `fastchat` library. However, [`fastchat` does not support `pydantic>=2`](https://github.com/lm-sys/FastChat/blob/6ff8505ec80fc4b04d668f65d229f4f58bc449e0/pyproject.toml#L17) so far and `pydantic.alias_generators`, which we used in https://github.com/camel-ai/camel/blob/c7ec055b24de32119243179bb9b6ea503d688c1f/camel/functions/openai_function.py#L21 is a feature of [`pydantic` 2.0](https://github.com/pydantic/pydantic/releases/tag/v2.0a4) which is not shown in current `pyproject.toml`.
https://github.com/camel-ai/camel/blob/c7ec055b24de32119243179bb9b6ea503d688c1f/pyproject.toml#L39
and we're also missing the requirement of `fschat` in `pyproject.toml` [link](https://github.com/camel-ai/camel/commit/7f0315f91a6891d6d7bcf78be0a7815f6a49f96c#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711).
If user add `fschat` at their local, `poetry` would find the minimum is `pydantic` 1.10.13 and caused the error above.

### Reproducible example code

None

### Traceback

```pytb
None
```

### Expected behavior

None

### Additional context

None

**Comment by lightaime** [comment]
Thanks for catching this bug. Could we just do ‘
`func.__name__.lower().replace("_", " ").title().replace(" ", "")` to convert to pascal cases?

**Comment by lightaime** [comment]
This is the source code. Maybe we can add it to utils.
```
def to_pascal(snake: str) -> str:
    """Convert a snake_case string to PascalCase.

    Args:
        snake: The string to convert.

    Returns:
        The PascalCase string.
    """
    camel = snake.title()
    return re.sub('([0-9A-Za-z])_(?=[0-9A-Z])', lambda m: m.group(1), camel)
```

**Comment by ocss884** [comment]
> This is the source code. Maybe we can add it to utils.
> 
> ```
> def to_pascal(snake: str) -> str:
>     """Convert a snake_case string to PascalCase.
> 
>     Args:
>         snake: The string to convert.
> 
>     Returns:
>         The PascalCase string.
>     """
>     camel = snake.title()
>     return re.sub('([0-9A-Za-z])_(?=[0-9A-Z])', lambda m: m.group(1), camel)
> ```

It looks not limited to `to_pascal`. Even more codes implicitly depends on pydantic V2
For example, in the same file
https://github.com/camel-ai/camel/blob/c7ec055b24de32119243179bb9b6ea503d688c1f/camel/functions/openai_function.py#L193-L194
This `ToolAssistantFunction` is from `openai` and [inherits](https://github.com/openai/openai-python/blob/ac33853ba10d13ac149b1fa3ca6dba7d613065c9/src/openai/types/beta/threads/run.py#L54) `openai` `BaseModel` which [inherits](https://github.com/openai/openai-python/blob/ac33853ba10d13ac149b1fa3ca6dba7d613065c9/src/openai/_models.py#L59) pydantic `BaseModel` now.

However, this `.model_validate` methods first appear in pydantic V2.0a1 (see this [commit](https://github.com/pydantic/pydantic/commit/f55515820a407c5d31c45a7b0307925eecf21f34#diff-8708af8d26c26644976866f974e0b810b0940ede43ff487e457057d5a1f07999)). Now openai only requires [pydantic >=1.9, <3](https://github.com/openai/openai-python/blob/ac33853ba10d13ac149b1fa3ca6dba7d613065c9/pyproject.toml#L12), that means if you are a pedantic V1 user, you would not have this validation methods when using `openai`.

**Comment by dandansamax** [comment]
Thank you for bug reporting. Sadly, I found a [pull request](https://github.com/lm-sys/FastChat/pull/2125) indicating fastchat will not upgrade their `pydantic` version very soon. I think the best solution may be change the camel code to be compatible with both pydantic v1 and v2.
