### ISSUE TITLE
[Feature Request] Integrate Claude 3

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#455]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Integrate Anthropic’s New LLM: [Claude 3 ](https://www.anthropic.com/claude)

**Comment by ocss884** [comment]
Maybe we can ship it together with #288 , I can help to add the support. @Wendong-Fan would you like to give a review of the current PR?

**Comment by Wendong-Fan** [comment]
Hey @ocss884, sure we can ship this one with #288 , sorry I didn't know we already has PR related, I will do the review and thanks for the contribution!
