### ISSUE TITLE
Finetuning code[Question] 

### ISSUE THREAD

**Issue by shrihari95** [camel-ai/camel#458]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

Can you release the code for finetuning various datasets like math, physics etc. in camel?

**Comment by lightaime** [comment]
Hi @shrihari95! The code is released here: https://github.com/camel-ai/camel_chat

**Comment by shrihari95** [comment]
Thanks @lightaime , this is helpful. Does train.py in camel_chat help with finetuning OSS models (LLama-7B as an example), on camel-ai datasets (Eg: https://huggingface.co/datasets/camel-ai/biology)?

**Comment by lightaime** [comment]
> Thanks @lightaime , this is helpful. Does train.py in camel_chat help with finetuning OSS models (LLama-7B as an example), on camel-ai datasets (Eg: https://huggingface.co/datasets/camel-ai/biology)?

yes, you can check https://github.com/camel-ai/camel_chat/blob/main/scripts/train_camel_7B.sh
