### ISSUE TITLE
[Question] Agents access function in role-play

### ISSUE THREAD

**Issue by Gunnar-Stunnar** [camel-ai/camel#487]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

Hi,

I am currently working on getting my agents access to a text documents that they would be reviewing and making edits on. I am having a hard time injecting the asset into there conversations. I tried writing a function and adding it like bellow but found no luck with the agents interacting or even knowing the function is accessible:

```python

def get_doc() -> str:
    # construct doc
    return doc

assistant_role_kwargs = {
    'assistant_role_name': '...',
    'assistant_agent_kwargs': {'model_type': ModelType.GPT_4_TURBO, "function_list":[OpenAIFunction(get_doc)]}
}
...
role_play_session = RolePlaying(
    **task_kwargs,
    **user_role_kwargs,
    **assistant_role_kwargs,
    # **critic_role_kwargs
)
```
When I run 
```python 
print(f"is assistant using function calling: " + str(role_play_session.assistant_agent.is_function_calling_enabled()))
```
I get
```
is assistant using function calling: True
```

Let me know if I am doing anything wrong or if this is not a feature yet.

**Comment by lightaime** [comment]
Hi @Gunnar-Stunnar. You may need to set the `model_config` with `FunctionCallingConfig` for using the function calling: https://github.com/camel-ai/camel/blob/master/examples/function_call/role_playing_with_function.py. 

It is a bit confusing. We will work on improving it. Let me know if there is any questions.

**Comment by Gunnar-Stunnar** [comment]
Perfect, it worked for me
