### ISSUE TITLE
[BUG] gradio No interface is running right now

### ISSUE THREAD

**Issue by robertgro** [camel-ai/camel#506]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.1.0

### System information

-

### Problem description

When visiting https://www.camel-ai.org/chat you get

![image](https://github.com/camel-ai/camel/assets/34941707/2eabaafc-8343-47a0-86d6-c21832a8911a)

### Reproducible example code

Steps to reproduce:

1. Visit https://www.camel-ai.org/chat

### Expected behavior

Working chat

### Additional context

Thank you anyways for your efforts!

**Comment by Wendong-Fan** [comment]
Hey @robertgro ,
Thanks for the issue and sorry for the late reply.
This service has been shut down.
