### ISSUE TITLE
[Question] Multi-domain dataset generation

### ISSUE THREAD

**Issue by shrihari95** [camel-ai/camel#528]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

Thanks for the great work. Using the camel-ai agents, would it be possible to create multi-domain datasets? Prompts that involve using a physics and chemistry agent (as an example) to answer. I could only find individual subjects so far.

**Comment by Wendong-Fan** [comment]
Hey @shrihari95 ,
Thanks for the issue and sorry for the late reply, you can refer to code in examples/ai_society/role_playing.py
Change the agent role name and task prompt to generate your customized dataset. Hope this answers your question
