### ISSUE TITLE
[Feature Request] Add Local LLM - Enhancement

### ISSUE THREAD

**Issue by Meathelix1** [camel-ai/camel#54]
Would love to be able to use local LLMS like Alpaca and Llama.

**Comment by lightaime** [comment]
@Meathelix1 Thanks for the suggestion. This will be done once we obtain a good open-source model.

**Comment by AestheticMayhem** [comment]
> @Meathelix1 Thanks for the suggestion. This will be done once we obtain a good open-source model.

any news on that, would love to let it run on local llm

**Comment by Terramoto** [comment]
Hey, would like to add most adaptations i've experienced for local LLM have been made by allowing to set openAI API URL, for instance oobabooga provides an openAI API format to communicate with supported models, so does AutoGPT.

**Comment by lightaime** [comment]
Hi @Terramoto, thanks for the great idea. It seems a lot of people are interested in this feature. Please feel free to open a PR on this!

**Comment by lightaime** [comment]
Supporting local models is to be added with this PR: https://github.com/camel-ai/camel/pull/245.
