### ISSUE TITLE
[Feature Request] Integrate Gemini 1.5

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#557]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Integrate Google Deepmind's latest multi modal model Gemini 1.5

refer: https://ai.google.dev/gemini-api?hl=zh-cn

**Comment by Asher-hss** [comment]
I would like to know if I should modify the subfolders directly under the camel folder or create a new subfolder under the camel folder if I want to integrate Gemini 1.5.

**Comment by Wendong-Fan** [comment]
> I would like to know if I should modify the subfolders directly under the camel folder or create a new subfolder under the camel folder if I want to integrate Gemini 1.5.

You can create one .py file under camel/models/
