### ISSUE TITLE
[Feature Request] Video input for Agent

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#567]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

enhance multi modal capability of Agent

**Comment by raywhoelse** [comment]
For now, GPT currently does not directly support video parsing. Videos need to be first parsed into images, and then multiple images can be parsed according to the SCI standard.
[https://platform.openai.com/docs/guides/vision](url)
