### ISSUE TITLE
[Question] poetry dependency list not up to date

### ISSUE THREAD

**Issue by petitchamp** [camel-ai/camel#586]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

I've forked the latest version but the code won't run after creating virtual env, several packages are missing

**Comment by Wendong-Fan** [comment]
Hey @petitchamp , please try `poetry install --with dev,docs -E all` to install all dependencies
