### ISSUE TITLE
[Feature Request] Integrate Together AI

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#629]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

integrate Together AI, cloud platform for building and running generative AI

**Comment by Wendong-Fan** [comment]
just noticed Together AI is supported by Litellm, refer: https://docs.litellm.ai/docs/providers/togetherai
maybe we don't need to do the integration by ourself and can close the issue? @lightaime @ocss884

**Comment by ocss884** [comment]
I'm ok with both solutions
