### ISSUE TITLE
[Feature Request] `Task` design and implementation

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#630]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

add `Task` to better manage multi agent work flow

### Solution

`Task`  can have  attribute like `description`, `expected_output`, `structured output schema`, `tools` specified to use
`Task` can be one type of `Message`
Need more research for better design on this

**Comment by onemquan** [comment]
The Task may need to be designed with planer Agent or `Master/control Agent` while is not supported currently.

**Comment by Wendong-Fan** [comment]
learn from https://docs.python.org/3/library/asyncio-task.html

**Comment by lightaime** [comment]
Task can be evolved, decomposed, generated.
