### ISSUE TITLE
[User demo Request] Audio conversion + text summary 

### ISSUE THREAD

**Issue by Pakchoioioi** [camel-ai/camel#641]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

In this tutorial demo, we need to build a meeting minutes bot to help users quickly grasp the main topics of lengthy meetings. Will need to use Camel's OpenAIAudioModels class to convert audio into text and then utilize Camel's summary tool to draft the meeting minutes.

**Comment by Wendong-Fan** [comment]
finished
