### ISSUE TITLE
 [Feature Request] Add a Converter to Standardize Output Formats

### ISSUE THREAD

**Issue by Asher-hss** [camel-ai/camel#650]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

To standardize the output format of various large language models, facilitating easier integration and comparison.

### Solution

Implement a converter to unify the output formats of different large language models, using OpenAI's output format as a reference.

**Comment by Wendong-Fan** [comment]
Since we will implement this feature within the model integration, this issue can be closed
