### ISSUE TITLE
[BUG]  ModuleNotFoundError for `pillow` and `unstructured` 

### ISSUE THREAD

**Issue by onemquan** [camel-ai/camel#673]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.1.5

### System information

3.10.14 (main, May  6 2024, 14:47:20) [Clang 14.0.6 ] darwin
0.1.5

### Problem description

    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

ModuleNotFoundError: No module named 'unstructured'

### Reproducible example code

Command lines:

```bash
python examples/ai_society/role_playing.py
```

### Expected behavior

the two libs should be installed by default, while not `optional`:

pillow = { version = "^10.2.0", optional = true }
unstructured = { extras = ["all-docs"], version = "^0.10.30", optional = true }

**Comment by Wendong-Fan** [comment]
Hey @onemquan , thanks for submitting this issue! Would you like to create one PR to solve this issue?
