### ISSUE TITLE
[Feature Request] Data connector

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#693]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

connect aws, huggingface, snowflake, databricks, azure, google drive

**Comment by Pakchoioioi** [comment]
【 Input & output data】
• Connect to an external data source using a workflow
    ◦ Amazon S3
    ◦ BigQuery
    ◦ Google Cloud Storage
    ◦ MySQL
    ◦ PostgreSQL
    ◦ Azure Blob
    ◦ Databricks
    ◦ MS SQL Server
    ◦ Oracle Database
    ◦ Snowflake
• Use a sample dataset via connection
    ◦ MySQL Sample Telecom Dataset
    ◦ S3 Sample Bucket

**Comment by Wendong-Fan** [comment]
Guohao:
2 usecase:
load dataset from storage, structured/unstructured -> generate data and store the data to storage

**Comment by Wendong-Fan** [comment]
also check what https://docs.unstructured.io/platform/platform-destination-connectors has
