### ISSUE TITLE
[Question] How do I change the code to make the program run math problems, or change my datasets to run？

### ISSUE THREAD

**Issue by Jayneh-yyds** [camel-ai/camel#697]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

I successfully followed the Readme and successfully ran python examples/ai_society/role_playing.py.
I want to run math problems, but I can't find the instructions.

**Comment by LysanderT** [comment]
Currently only AcademicAgent is active; the other agents have been commented out due to financial constraints lol
