### ISSUE TITLE
[Feature Request] Remove torch from CAMEL dependency

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#728]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

torch is too heavy and not used regular, test whether we can remove torch

**Comment by onemquan** [comment]
we can check all of the dependency by command: `poetry show --tree` 
and the below libs used `torch`:
- accelerate
- diffusers
- sentence-transformers
- transformers
- unstructured

And all of the libs are set to optional installation `optional = true`.
so, if the camel users install the camel lib by `pip install camel-ai` or `pip install -e .` , the torch lib will not be installed.
if the users install the camel in a dev mode, the `torch` should be installed.

SO, I think we can keep our current setting. I

**Comment by onemquan** [comment]
the `unstructured` required the `torch` library to be installed.  [ref](https://github.com/Unstructured-IO/unstructured-inference/blob/main/requirements/base.txt).  
so we can not remove the `torch` if we need `unstructured` .
