### ISSUE TITLE
[Feature Request] Support function calling for any open source models

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#735]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

1. constrained generation
2. one more step to convert content from model to function call content

Need more study for this

**Comment by lightaime** [comment]
refs: https://ollama.com/blog/tool-support

**Comment by Wendong-Fan** [comment]
close as finished by @Wendong-Fan
