### ISSUE TITLE
[BUG] huggingface.co  spaces  camel-agents  ERROR

### ISSUE THREAD

**Issue by zhengshifa** [camel-ai/camel#738]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.1

### System information

ERROR LINK https://huggingface.co/spaces/camel-ai/camel-agents

### Problem description

ERROR LINK https://huggingface.co/spaces/camel-ai/camel-agents

### Reproducible example code

ERROR LINK https://huggingface.co/spaces/camel-ai/camel-agents

**Comment by Wendong-Fan** [comment]
Thanks @zhengshifa  for raising this issue! The app is back to live now

https://huggingface.co/spaces/camel-ai/camel-agents
