### ISSUE TITLE
[Feature Request] Integrate What's App

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#740]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

different with working spaces like slack and discord, what's app is also popular used, we need to do some support for what's app

**Comment by Coder-Joe458** [comment]
I am interested contributing to this issue. Would like to help.

**Comment by Wendong-Fan** [comment]
> I am interested contributing to this issue. Would like to help.

Thanks @Coder-Joe458 ! I will assign this issue to you, @Asher-hss hasn't started working on this, you can refer to our contribution [guideline](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) and refer to the code for similar features like https://github.com/camel-ai/camel/pull/886/files and https://github.com/camel-ai/camel/pull/839/files

If you have any further questions don't hesitate to reach out to me in slack or discord, thanks for the contribution!
