### ISSUE TITLE
[Question] How can I run the multi-agent framework?

### ISSUE THREAD

**Issue by kakaxi-liu** [camel-ai/camel#751]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

Is there a demo for multi-agent framework?
![c40208b20871e7d52a33d7c3bc106af](https://github.com/user-attachments/assets/5e80916c-2814-404d-b37a-d3a6d4d7ceff)

**Comment by Wendong-Fan** [comment]
Hey @kakaxi-liu ,

Thanks for the question! For now you can run our example code in the repo for role playing including different agents, here is the path examples/ai_society/role_playing.py
For the supporting of more agents working together we have one PR ongoing here: https://github.com/camel-ai/camel/pull/713, this feature would be added to CAMEL soon~

Feel free to reopen this issue if you have any further questions and thanks for using CAMEL!
