### ISSUE TITLE
[BUG] GPT 3.5 Turbo Token Limit value seems incorrect

### ISSUE THREAD

**Issue by Georgelingzj** [camel-ai/camel#768]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.1.5.7

### System information

0.1.5.7

### Problem description

![WechatIMG1266](https://github.com/user-attachments/assets/078d194b-aa51-47f2-97b4-5eedbf9a5bbd)
![WechatIMG1267](https://github.com/user-attachments/assets/bb22d309-cf46-409e-93a1-77f4465a995e)

### Reproducible example code

No code is required to reproduce this.

**Comment by Wendong-Fan** [comment]
thanks @Georgelingzj  for raising this issue! Will fix this soon
