### ISSUE TITLE
[Feature Request] Allow user to import one single tool from `toolkits` by importing each tool in `toolkits.__init__`

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#775]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

**Comment by Wendong-Fan** [comment]
```
from camel.toolkits import SearchToolkit

google_tool = OpenAIFunction(SearchToolkit().search_google)
wiki_tool = OpenAIFunction(SearchToolkit().search_wiki)
```
