### ISSUE TITLE
[Feature Request] Enhance the Chat Message's compatibility with multimodal content (text, images, video)

### ISSUE THREAD

**Issue by Appointat** [camel-ai/camel#806]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Camel-AI currently utilizes OpenAIMessage for message passing, which supports text and image content. However, as open-source multi-modal large language models (InternLM-XComposer) continue to evolve, there is a growing need for a more versatile message structure.

This issue proposes the creation of a new message data structure that can accommodate:

- Text content
- Images
- Video

, in order to enable compatibility with advanced multi-modal models.

**Comment by Wendong-Fan** [comment]
close this issue as finished in https://github.com/camel-ai/camel/pull/787
