### ISSUE TITLE
[Question] track_agent() got an unexpected keyword argument 'name' when without agentops

### ISSUE THREAD

**Issue by coolbeevip** [camel-ai/camel#807]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

The track_agent function is defined in multiple files to provide a no-operation function when the agentops package is not imported. 

However, this function does not handle any arguments, including the name argument used in the @track_agent(name="xxx") decorator. This could lead to errors when running the code in an environment without the agentops package.  I suggest we move the definition of the track_agent function to a standard module and modify it to accept and ignore all arguments. This way, we can import and use it wherever needed without redefining it in each file. It would also prevent potential errors due to the unhandled name argument.  

Here's my proposed new definition for the track_agent function:

```python
def track_agent(*args, **kwargs):
    def noop(f):
        return f
    return noop
```

BTW: this is an exciting repos

**Comment by Wendong-Fan** [comment]
Thanks @coolbeevip ! The issue has been solved
