### ISSUE TITLE
[Feature Request] Structured output supported by Openai

### ISSUE THREAD

**Issue by Appointat** [camel-ai/camel#821]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Introducing Structured Outputs in the API.

Refer to: https://openai.com/index/introducing-structured-outputs-in-the-api/

**Comment by Wendong-Fan** [comment]
close as finished by @Wendong-Fan
