### ISSUE TITLE
[Question] Together AI

### ISSUE THREAD

**Issue by dangyuuki123** [camel-ai/camel#853]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

I am using togerther AI service, is there any way to use Togerther Ai for CAMEL? can you give me an example?

**Comment by Wendong-Fan** [comment]
Hey @dangyuuki123 , we have one PR to support Together AI here: https://github.com/camel-ai/camel/pull/843
If you have time you can also help with the code review, this feature will be added to CAMEL this week
