### ISSUE TITLE
[Feature Request] Update naming for OpenAIFunction

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#858]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

The class "OpenAIFunction" doesn't actually require OpenAI, it's a legacy name from earlier development.we can renaming it to something more fitting, like "CamelTool."

**Comment by tom-doerr** [comment]
I would like to give this a try, could you assign it to me?

**Comment by Wendong-Fan** [comment]
Hey @tom-doerr , thank you for your willingness to contribute! We're planning to rename OpenAIFunction to FunctionTool. However, if you have any alternative name suggestions, we’re open to discussing them. I've assigned this issue to you.

**Comment by tom-doerr** [comment]
I renamed OpenAIFunction to FunctionTool. 
However not all tests pass for me, even before I renamed it, see discussion: https://github.com/orgs/camel-ai/discussions/910

**Comment by Wendong-Fan** [comment]
> I renamed OpenAIFunction to FunctionTool. However not all tests pass for me, even before I renamed it, see discussion: https://github.com/orgs/camel-ai/discussions/910

Thanks @tom-doerr! You can create the PR directly, if the failed test is not related to your change but just due to lack for API Keys then we can ignore those failed test

**Comment by tom-doerr** [comment]
Just added a PR that is almost just renaming OpenAIFunction. 
There are however still functions that include openai, e.g.
```
    def validate_openai_tool_schema(
```
I also worked on renaming those and renaming the files that are referencing OpenAI functions, however that breaks backwards compatibility.
Should I rename them and add the old function/filenames that throw a deprecation warning when used?

**Comment by Wendong-Fan** [comment]
thanks @tom-doerr ! For this method it's indeed related to OpenAI since it's validating whether the schema follow's OpenAI's required format, so I'd suggest don't rename this method
