### ISSUE TITLE
[Feature Request] RAG on Github repos including code, issues and PRs

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#866]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Some of the functionalities are already supported.

https://github.com/camel-ai/camel/blob/master/camel/toolkits/github_toolkit.py

**Comment by Wendong-Fan** [comment]
close as finished by @raywhoelse
