### ISSUE TITLE
[Feature Request] OpenAI organization account setting

### ISSUE THREAD

**Issue by histmeisah** [camel-ai/camel#870]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Solution

Currently, I am utilizing an organizational account with OpenAI. However, I have encountered an issue where there seems to be no option available to configure my organizational account settings as outlined in the OpenAI documentation. Below is the code snippet I am using:
```
        self.client = OpenAI(
            api_key=get_config("openai", "api_key"),
            organization=get_config("openai", "organization_id")
        )
```
Could you please consider adding support for the organizational API in future updates? This feature would greatly enhance usability for organizational account holders. Thank you!

### Additional context

openai official document:
https://platform.openai.com/docs/api-reference/authentication

section:https://platform.openai.com/docs/api-reference/organizations-and-projects-optional

**Comment by Wendong-Fan** [comment]
<img width="711" alt="image" src="https://github.com/user-attachments/assets/6353d6df-8e41-47a8-9976-87ea814fa961">

close this issue since the setting can be done by using environment variables
