### ISSUE TITLE
[Feature Request] Tutorials on core modules 

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#887]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Tutorials on core modules

**Comment by fengju0213** [comment]
Are there any reference cases?

**Comment by Wendong-Fan** [comment]
Hey @fengju0213  really sorry for the late reply,
here are some tutorial PRs ready for review:
https://github.com/camel-ai/camel/pull/909
https://github.com/camel-ai/camel/pull/908
https://github.com/camel-ai/camel/blob/add_cookbook/cookbooks/agents_with_tools.ipynb
https://github.com/sallyqus/camel/blob/patch-1/docs/key_modules/models.md
https://github.com/camel-ai/camel/pull/914
https://github.com/camel-ai/camel/pull/901

If you have time please check the content that you are interested in, thanks in advance!

**Comment by Wendong-Fan** [comment]
finished in https://github.com/camel-ai/camel/commit/db019bbbaf2cbc6b4510b65d0d3d6e620341cc86
