### ISSUE TITLE
[Feature Request] More comprehensive support for Github Toolkits

### ISSUE THREAD

**Issue by Wendong-Fan** [camel-ai/camel#922]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Current Github toolkits supports
```
            OpenAIFunction(self.retrieve_issue_list),
            OpenAIFunction(self.retrieve_issue),
            OpenAIFunction(self.create_pull_request),
            OpenAIFunction(self.retrieve_pull_requests),
```
we need to further support code pulling

**Comment by WHALEEYE** [comment]
duplicated with #866, closed
