### ISSUE TITLE
Add different language support for `role-playing`

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#93]

**Comment by lightaime** [comment]
Hi @kanukolluGVT, for achieving this. We should only need to modify the prompt. If you are interested in helping with this issue. We can collaborate on this. Thanks!

**Comment by kanukolluGVT** [comment]
Sure, I'm happy to help! Can you give me more details about what you want to modify in the prompt and what exactly the issue is?

**Comment by lightaime** [comment]
This is fixed: https://github.com/camel-ai/camel/pull/181.
