### ISSUE TITLE
[Feature Request] Support auto tool schema or docstring generation for `OpenAIFunction`

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#949]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

Sometime users do not want to write a docstring for when creating the tools. Supporting auto tool schema or docstring generation for `OpenAIFunction` would be helpful.

**Comment by Wendong-Fan** [comment]
solution: user give one function without docstring, LLM generate docstring automaticlly

**Comment by Wendong-Fan** [comment]
Guohao: when tools defined without docstring, we add docstring based on the code

user function - generate docstring stored in attribute / do tool calling generate docstring > camel tool
