### ISSUE TITLE
[Feature Request] A unify api key management for tools

### ISSUE THREAD

**Issue by lightaime** [camel-ai/camel#950]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

It is difficult for users to create all api keys for tools. We can have a unified api key for users to use all available tools in CAMEL.

This feature maybe some research and design.

**Comment by Wendong-Fan** [comment]
for new features we need to maintain the api key list

**Comment by Wendong-Fan** [comment]
comment from @koch3092 , we can use Pydantic setting to manage this
