### ISSUE TITLE
[BUG] Cannot install using the latest version of python or the second to latest (3.11 or 3.12)

### ISSUE THREAD

**Issue by TheOtherRealm** [camel-ai/camel#967]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

.2.1a

### System information

3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:42:31) [MSC v.1937 64 bit (AMD64)] win32

### Problem description

Cannot install using the latest version of python or the second to latest (3.11 or 3.12)

### Reproducible example code

Command lines:
```bash
pip install 'camel-ai[all]'
ERROR: Ignored the following versions that require a different python version: 0.1.1 Requires-Python >=3.8.1,<3.12; 0.1.3 Requires-Python <3.12,>=3.8.1; 0.1.4 Requires-Python <3.12,>=3.8.1; 0.1.5 Requires-Python <3.12,>=3.8.1; 0.1.5.1 Requires-Python <3.12,>=3.8.1; 0.1.5.2 Requires-Python <3.12,>=3.8.1; 0.1.5.3 Requires-Python <3.12,>=3.8.1; 0.1.5.4 Requires-Python <3.12,>=3.9.0; 0.1.5.5 Requires-Python <3.12,>=3.9.0; 0.1.5.6 Requires-Python <3.12,>=3.9.0; 0.1.5.7 Requires-Python <3.12,>=3.9.0; 0.1.5.9 Requires-Python <3.12,>=3.9.0; 0.1.6.0 Requires-Python <3.12,>=3.9.0; 0.1.6.1 Requires-Python <3.12,>=3.9.0; 0.1.6.2 Requires-Python <3.12,>=3.9.0; 0.1.6.3 Requires-Python <3.12,>=3.9.0; 0.1.6.4 Requires-Python <3.12,>=3.9.0; 0.1.6.5 Requires-Python <3.12,>=3.9.0; 0.1.6.6 Requires-Python <3.12,>=3.9.0; 0.1.6.7 Requires-Python <3.12,>=3.9.0; 0.1.6.8 Requires-Python <3.12,>=3.10.0; 0.1.6.9 Requires-Python <3.12,>=3.10.0; 0.1.7.0 Requires-Python <3.12,>=3.10.0; 0.1.7.1 Requires-Python <3.12,>=3.10.0; 0.1.7.2 Requires-Python <3.12,>=3.10.0; 0.1.8 Requires-Python <3.12,>=3.10.0; 0.1.9 Requires-Python <3.12,>=3.10.0; 0.2.0 Requires-Python <3.12,>=3.10.0; 0.2.1 Requires-Python <3.12,>=3.10.0; 0.2.1a0 Requires-Python <3.12,>=3.10.0
ERROR: Could not find a version that satisfies the requirement camel-ai[all] (from versions: none)
ERROR: No matching distribution found for camel-ai[all]
```

Steps to reproduce:

1. Be using python 3.12
2. try to install all dependencies using pip

### Expected behavior

It installs correctly using python 3.12

### Additional context

I can install using python 3.10, but not 3.11 or 3.12

**Comment by Wendong-Fan** [comment]
Thanks for raising this issue @TheOtherRealm ! Actually CAMEL doesn't support python v 3.12, we require python = ">=3.10.0,<3.12" for 3.11 it should be fine

**Comment by Wendong-Fan** [comment]
<img width="915" alt="Screenshot 2024-09-20 at 03 54 57" src="https://github.com/user-attachments/assets/f3fa0029-ec3c-4368-9525-5c82eb1198b0">
I tested python 3.11 in a new environment it works from my side, I will close this issue and if you have any further questions feel free to reopen this issue, thanks!
