### ISSUE TITLE
[Feature Request] Onboarding agent doc. Add guidance on how to use the OpenAI compatible api.

### ISSUE THREAD

**Issue by LuciusMos** [camel-ai/camel#988]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Motivation

I am a new user of camel. When reading the agent-building doc for onboarding, I found there is no guidance on how I could use an OpenAI compatible api (In my case, I used [deepseek api](https://platform.deepseek.com/api-docs/), which is quite popular for its strong performance and low price). And even worse, the current doc is a bit misleading. Here is how the doc says [doc link](https://docs.camel-ai.org/get_started/setup.html#unix-like-system-linux-macos)

```
echo 'export OPENAI_API_KEY="your_api_key"' >> ~/.zshrc

# If you are using other proxy services like Azure
echo 'export OPENAI_API_BASE_URL="your_base_url"' >> ~/.zshrc # (Optional)
``` 

Because deepseek api uses `api_key="<DeepSeek API Key>", base_url="https://api.deepseek.com"`, which is compatible with OpenAI api, so I used the command line above to set env variable. However, it does not work. I think the reason is that, for the `ChatAgent` code in the doc, we do not pass a model, so it would use the default one, which only permits OpenAI api rather than other compatible ones [code link](https://github.com/camel-ai/camel/blob/master/camel/agents/chat_agent.py#L164):

```python
            else ModelFactory.create(
                model_platform=ModelPlatformType.OPENAI,
                model_type=ModelType.GPT_4O_MINI,
                model_config_dict=ChatGPTConfig().as_dict(),
            )
``` 

So I used `OpenAICompatibilityModel` to initialize a customized model and pass it into the `ChatAgent` and it worked, like the code below: (I stored the base url and key in `.env` file, and used `load_dotenv()` to load)

```python
agent = ChatAgent(
    system_message=sys_msg,
    message_window_size=10,    # [Optional] the length for chat memory
    model=OpenAICompatibilityModel(
        model_type="deepseek-chat",
        model_config_dict={"max_tokens": 4096},
        api_key=os.getenv("OPENAI_API_KEY"),
        url=os.getenv("OPENAI_API_BASE_URL"),
    )
)
``` 

I think there would be many users who face similar confused situation like me. So I think we should modify the onboarding doc and give more detailed guidance on how to use OpenAI compatible apis.

### Solution

1. Add more api guide here: [API Setup doc](https://docs.camel-ai.org/get_started/setup.html#api-setup), including other apis besides OpenAI, OpenAI compatible api. Also for the local open-source model part, we can add vLLM here, which I found elsewhere in the doc. Or, we can link to the [Model doc](https://docs.camel-ai.org/key_modules/models.html#), and explain in detail there.
2. Separate the API Setup part. So the "Get Started" would be like:
```
- Get Started
    - Installation
        - ...
    - Model Setup
        - API
        - Local Model
```

**Comment by Wendong-Fan** [comment]
Thanks @LuciusMos ! The 2nd solution your proposed looks better to me, we can make `Installation and Setup` part with better structured, I also think we can support environment variable passing for `OpenAICompatibilityModel `, like `OPENAI_COMPATIBILIY_API_KEY ` and  `OPENAI_COMPATIBILIY_API_KEY`, also mention this in [doc for model ](https://docs.camel-ai.org/key_modules/models.html), could you help with this?

**Comment by LuciusMos** [comment]
> Thanks @LuciusMos ! The 2nd solution your proposed looks better to me, we can make `Installation and Setup` part with better structured, I also think we can support environment variable passing for `OpenAICompatibilityModel `, like `OPENAI_COMPATIBILIY_API_KEY ` and `OPENAI_COMPATIBILIY_API_KEY`, also mention this in [doc for model ](https://docs.camel-ai.org/key_modules/models.html), could you help with this?

@Wendong-Fan Thanks for the feedback! Yeah of course I would work on this with a new PR

**Comment by Wendong-Fan** [comment]
close as finished by @LuciusMos
